# Generated by Django 3.0.7 on 2020-08-24 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interiorwebsite', '0002_cutomer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cutomer',
        ),
    ]
