# Generated by Django 3.0.7 on 2020-08-24 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interiorwebsite', '0006_cutomer'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContectDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
            ],
        ),
    ]
