# Generated by Django 3.0.7 on 2020-09-03 15:47

from django.db import migrations, models
import interiorwebsite.table_creation


class Migration(migrations.Migration):

    dependencies = [
        ('interiorwebsite', '0008_contect'),
    ]

    operations = [
        migrations.CreateModel(
            name='passenger_movement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', interiorwebsite.table_creation.DateTimeWithoutTZField(auto_now_add=True)),
                ('ArrivalsActualCounts', models.IntegerField()),
                ('DeparturesActualCounts', models.IntegerField()),
            ],
        ),
    ]
