# Generated by Django 3.0.7 on 2020-09-04 13:16

from django.db import migrations
import interiorwebsite.table_creation


class Migration(migrations.Migration):

    dependencies = [
        ('interiorwebsite', '0012_passenger_movements'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passenger_movements',
            name='id',
        ),
        migrations.AlterField(
            model_name='passenger_movements',
            name='Date',
            field=interiorwebsite.table_creation.DateTimeWithoutTZField(primary_key=True, serialize=False),
        ),
    ]
