# Generated by Django 3.0.7 on 2020-09-04 13:18

from django.db import migrations
import interiorwebsite.table_creation


class Migration(migrations.Migration):

    dependencies = [
        ('interiorwebsite', '0013_auto_20200904_1846'),
    ]

    operations = [
        migrations.DeleteModel(
            name='passenger_movements',
        ),
        migrations.RemoveField(
            model_name='passenger_movement',
            name='id',
        ),
        migrations.AlterField(
            model_name='passenger_movement',
            name='Date',
            field=interiorwebsite.table_creation.DateTimeWithoutTZField(primary_key=True, serialize=False),
        ),
    ]
