# Generated by Django 3.0.7 on 2020-09-04 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interiorwebsite', '0014_auto_20200904_1848'),
    ]

    operations = [
        migrations.DeleteModel(
            name='passenger_movement',
        ),
    ]
