# Generated by Django 3.0.7 on 2020-09-04 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interiorwebsite', '0016_passenger_movement'),
    ]

    operations = [
        migrations.DeleteModel(
            name='passenger_movement',
        ),
    ]
