# Generated by Django 3.0.7 on 2020-09-04 19:45

from django.db import migrations, models
import interiorwebsite.table_creation


class Migration(migrations.Migration):

    dependencies = [
        ('interiorwebsite', '0017_delete_passenger_movement'),
    ]

    operations = [
        migrations.CreateModel(
            name='passenger_movement',
            fields=[
                ('Date', interiorwebsite.table_creation.DateTimeWithoutTZField(primary_key=True, serialize=False)),
                ('ArrivalsActualCounts', models.IntegerField()),
                ('DeparturesActualCounts', models.IntegerField()),
            ],
        ),
    ]
