# Generated by Django 3.0.7 on 2020-09-04 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interiorwebsite', '0018_passenger_movement'),
    ]

    operations = [
        migrations.RenameField(
            model_name='passenger_movement',
            old_name='ArrivalsActualCounts',
            new_name='arrivals_counts',
        ),
        migrations.RenameField(
            model_name='passenger_movement',
            old_name='DeparturesActualCounts',
            new_name='departures_counts',
        ),
    ]
