# Generated by Django 3.0.7 on 2020-09-04 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interiorwebsite', '0019_auto_20200905_0120'),
    ]

    operations = [
        migrations.DeleteModel(
            name='passenger_movement',
        ),
    ]
