# Generated by Django 3.0.7 on 2020-09-04 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interiorwebsite', '0021_passenger_movement'),
    ]

    operations = [
        migrations.RenameField(
            model_name='passenger_movement',
            old_name='arrivals_counts',
            new_name='ArrivalsActualCounts',
        ),
        migrations.RenameField(
            model_name='passenger_movement',
            old_name='departures_counts',
            new_name='DeparturesActualCounts',
        ),
    ]
